name: artacode_challenge_app
description: "This is a challenge app by AmirAbbas Jannatian for artacode"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  intl: ^0.20.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/font/Yekan-Bakh-FaNum-04-Regular.ttf
          weight: 400
        - asset: assets/font/Yekan-Bakh-FaNum-06-Bold.ttf
          weight: 600